add: emailかpasswordの間違いを指摘するerrorを追加
arumakan1727/taskrader pull request #23
Opened 2022-01-24 10:26 UTC by kajikaji0725

## Issueへのリンク
[#19](https://github.com/arumakan1727/taskrader/issues/19)

## 確認してほしいこと
- emailかpasswordを間違えたときに、わかるようにerrorが返ってきているかどうか。

## 注意点・気になっている点・不安な点 (もしあれば)
- teamsのような実装方法ではなくgetTokenでStatusCodeが200以外ならemailかpasswordが間違えていると仮定の下で実装している。本当にそれが正しいのかどうかがわからない。

2022-01-24 11:37 UTC, arumakan1727 reviewed
login_test.go にこんな感じのテストコードを入れてくれると嬉しいです！

```go
func TestEdstemWrongPasswd(t *testing.T) {
	c := edstem.NewClient()
	err := c.Login(email, password+"wrong_password")

	switch err.(type) {
	case *edstem.ErrEmailOrPasswdWrong:
		e := err.(*edstem.ErrEmailOrPasswdWrong)  // 型をキャスト
		if e.Email != email {
			t.Errorf("err.Email: Expected %s, but got %s", email, e.Email)
		}
		break

	default:
		t.Errorf("Expected *edstem.ErrEmailOrPasswdWrong, but got %v", err)
	}
}
```

2022-01-24 11:38 UTC, arumakan1727 requested changes
以上3つお願いします :bow: 
getToken の statusCode が 200 かどうかの判定で問題ないと思います :+1:

2022-01-26 17:00 UTC, arumakan1727 approved these changes

2022-01-26 17:01 UTC, merged

2024-12-30 12:15 UTC, Tommyredfilm reviewed
Tommy